### PR TITLE
Update to 0.0.1 for first release

### PR DESCRIPTION
**Pull request by uzadude**
## Release trial

### CODE REVIEW

**Comment by shay1bz** [comment]
shouldn't this be 0.0.1-SNAPSHOT in main?  or 0.0.2-SNAPSHOT?

**Comment by uzadude** [comment]
the SNAPSHOT already works. i just want to see that the release also works.
afterwards i will release a "real" one with `0.5` for spark-2.3

**Comment by shay1bz** [comment]
yeah but why merge this to main? I remember we said to release only from release branches

**Comment by uzadude** [comment]
ok, you're right.
I will go to a 0.5-release branch and fix the deploy job.

**Pull request closed without merging**
