### PR TITLE
Trying to upgrade to Spark 3.3

### LINKED ISSUE #82: Any plan to upgrade the spark version to 3.3.0 ?
## Summary
As we're going to migrate to gcp dataproc 2.1, it would be awesome to have dione upgrade first.

Links to #PR/#Issue

## Detailed Description

what is the problem?
how can we solve it?

### PR DESCRIPTION
**Pull request by uzadude**
## Summary

resolves #82

### CODE REVIEW

**Comment by shay1bz** [comment]
Why is there jackson dependency,  anyway? Doesn't it come with Spark?

**Comment by uzadude** [comment]
@forshareIT - finally got it to pass. could you please verify that it works on your end?

**Comment by forshareIT** [comment]
@uzadude  Sure! Thank you Ohad for always being reliable!!

**Comment by forshareIT** [comment]
@uzadude Finished the test and everything looks good! 
Also opened a [PR](https://github.com/paypal/dione/pull/84) to upgrade avro(included in spark 3.3.0), could you help to have a look when you're free?

**Comment by uzadude** [comment]
@forshareIT - sure, merged your PR!
so I understand we can merge and release based on this PR, right?

**Comment by forshareIT** [comment]
> 

Yes, let's do it!

**Comment by forshareIT** [comment]
> @forshareIT - sure, merged your PR! so I understand we can merge and release based on this PR, right?

Yes @uzadude ! Just in case you missed the reply.

**Comment by eyala** [comment]
I'm not planning a release, but there's no reason not to

**Comment by forshareIT** [comment]
Hi @uzadude / @eyala , do we have any concern of the release? Pls let me know if anything I can help! Thanks!

**Comment by uzadude** [comment]
hei @forshareIT - sorry was a bit busy lately and we had a permission issue.
but we've merged and released 0.8.0!

**Comment by forshareIT** [comment]
Hi @uzadude , no problem! Take your time!
Just want to let you know that I'm available for the releasing part too. If any tips/rules need to be take care of, willing to have a check on that. Haha

**Comment by uzadude** [comment]
no need, already released - https://repo1.maven.org/maven2/com/paypal/dione/dione-hadoop/0.8.0/dione-hadoop-0.8.0.jar

**Pull request merged**
